# Generated by Django 5.2.4 on 2025-08-05 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='製品名')),
                ('model_name', models.CharField(max_length=100, verbose_name='モデル名')),
                ('design_site', models.CharField(blank=True, max_length=100, null=True, verbose_name='設計拠点')),
                ('MPAN_date', models.DateField(blank=True, null=True, verbose_name='MPAN年月')),
            ],
            options={
                'verbose_name': 'モデル情報',
                'verbose_name_plural': 'モデル情報',
                'ordering': ['product_name', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='Kakotora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('category', models.CharField(max_length=50, verbose_name='カテゴリ')),
                ('status', models.CharField(max_length=50, verbose_name='ステータス')),
                ('content', models.JSONField(blank=True, null=True, verbose_name='内容')),
                ('mechanism', models.JSONField(blank=True, null=True, verbose_name='メカニズム')),
                ('cause_occurrence', models.JSONField(blank=True, null=True, verbose_name='発生原因')),
                ('cause_outflow', models.JSONField(blank=True, null=True, verbose_name='流出原因')),
                ('temporary_action', models.JSONField(blank=True, null=True, verbose_name='暫定対策')),
                ('permanent_action', models.JSONField(blank=True, null=True, verbose_name='恒久対策')),
                ('horizontal_deployment', models.JSONField(blank=True, null=True, verbose_name='水平展開')),
                ('reference_link', models.URLField(blank=True, null=True, verbose_name='参考リンク')),
                ('reference_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='参考パス')),
                ('reference_file', models.FileField(blank=True, null=True, upload_to='reference_files/', verbose_name='参考ファイル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('model_names', models.ManyToManyField(related_name='kakotora_models', to='kakotora.modelname', verbose_name='モデル名')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kakotora_products', to='kakotora.modelname', verbose_name='製品名')),
            ],
            options={
                'verbose_name': '過去トラ',
                'verbose_name_plural': '過去トラ',
                'ordering': ['-updated_at'],
            },
        ),
    ]
